version: '3.7'

################################################################################
# NETWORKING CONFIGURATION
################################################################################

networks:

    traefik:
        external:
            name: traefik_reverse-proxy

################################################################################
# SERVICES CONFIGURATION
################################################################################

services:

    ####################################
    # HOSTED JUPYTER NOTEBOOK
    ####################################

    jupyter:
        container_name: jupyter
        build:
            context:    ${DOCKER_DIRECTORY}/jupyter/
            dockerfile: Dockerfile
        networks:
            traefik: null
        restart:        ${UNIVERSAL_RESTART_POLICY}
        user:           root
        working_dir:    /home/${ADMIN_USER}
        environment:
            NB_USER:               ${ADMIN_USER}
            NB_UID:                ${PUID}
            NB_GID:                ${PGID}
            JUPYTER_ENABLE_LAB:    "yes"
            RESTARTABLE:           "yes"
            CHOWN_HOME:            "yes"
            GRANT_SUDO:            "yes"
            JUPYTER_TOKEN:         ${ADMIN_PASSWORD}
            PYTHONPATH:            $${PYTHONPATH}:/home/${ADMIN_USER}/${SHARED_DIRECTORY_NAME}
        volumes:
            - ${SHARED_DIRECTORY}:/home/${ADMIN_USER}/${SHARED_DIRECTORY_NAME}:rw
        command:        start.sh jupyter lab
        labels:
            traefik.enable:                                             true
            traefik.http.routers.jupyter-rtr.rule:                      Host(`${JUPYTER_SUBDOMAIN}.${DOMAIN_NAME}`)
            traefik.http.routers.jupyter-rtr.service:                   jupyter-svc
            traefik.http.services.jupyter-svc.loadbalancer.server.port: 8888
            # SET ENTRYPOINTS TO "HTTP" AND COMMENT OUT MIDDLEWARE LINE WHEN RUNNING LOCALLY
            traefik.http.routers.jupyter-rtr.entrypoints:               https
            traefik.http.routers.jupyter-rtr.middlewares:               chain-oauth-google@file